language: generic

dist: bionic

env:
  global:
    - ROS_DISTRO="melodic"
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - UPSTREAM_WORKSPACE=file
    - BUILD_PKGS_WHITELIST="bwi_common"
    - DB_BACKEND="PostgreSQL"
  matrix:
    - ROS_DISTRO="melodic"

services:
  - postgresql

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b legacy
script:
  - .industrial_ci/travis.sh
